services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    mem_limit: 128m
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  # 블루 배포
  app-blue:
    image: ${APP_IMAGE:-ccapp:latest}
    container_name: ccapp-blue
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m"
    restart: unless-stopped
    pull_policy: always
    mem_limit: 800m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

  app-green:
    #그린 배포
    image: ${APP_IMAGE:-ccapp:latest}
    container_name: ccapp-green
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m"
    restart: unless-stopped
    pull_policy: always
    mem_limit: 800m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
