#application.yml
server:
  port: 8080
  forward-headers-strategy: native
spring:
  profiles:
    default: ${SPRING_PROFILES_ACTIVE} # 기본 실행 환경
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Google
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379


url:
  access-token: https://oauth2.googleapis.com/token
  profile: https://www.googleapis.com/oauth2/v2/userinfo



jwt:
  secret: ${JWT_SECRET}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:5173/auth/kakao/callback}

kakaopay:
  secret-key: ${KAKAOPAY_SECRET_KEY}
  cid: TC0ONETIME
  base-url: https://open-api.kakaopay.com
  url:
    approval: ${KAKAOPAY_APPROVE_URL}
    cancel: ${KAKAOPAY_CANCEL_URL}
    fail: ${KAKAOPAY_FAIL_URL}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

admin:
  password: ${DEFAULT_PW}